; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:agafia_sg0]
platform = ststm32
board = agafia_sg0

; [env:SIGMA_MDC_G0]
; platform = ststm32
; board = sigma_ic_g071cb


framework = arduino

upload_protocol = stlink 
upload_flags = 
	;-c ;<--This is only need if you are using the china clone of bluepill
	;set CPUTAPID 0x2ba01477 ; <--This is only need if you are using the china clone of bluepill
	-c
	;adapter serial 003800193431511631343632  ; <-- this is *Sigma LDH* STLink
	;adapter serial 52FF6D065089485451311387 ; <-- this is *Pink color* STLink 
	adapter serial 001C00283232511739353236 ; <-- this is *STLink V3 Mini* STLink
	;hla_serial 52FF6D065089485451311387     ; <-- Replace with your ST-link SN

lib_deps =  
	stm32duino/STM32duino RTC@^1.3.2
	stm32duino/STM32duino Low Power@^1.2.2
	m-tech-creations/NoDelay@^2.1.1